package:
  name: qdyn
  version: "3.0.0"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip

  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy
    - pandas
    - termcolor
    - jupyter
    - matplotlib

test:
  imports:
    - qdyn
    - qdyn.utils

about:
  license: GPLv3

